### ISSUE TITLE
Question about ingress controller

### ISSUE THREAD

**Issue by homesith** [nginxinc/nginx-loadbalancer-kubernetes#111]
Hello,

One question, can this project work with [Ingress nginx](https://github.com/kubernetes/ingress-nginx) or does it only function with [Nginx Inc](https://docs.nginx.com/nginx-ingress-controller/) controller?

Thank you!

**Comment by ciroque** [comment]
Hi @homesith , while we have not strictly tested NLK with either of those solutions, NLK is mostly orthogonal to Ingress nginc and Nginx Ingress Controller.

We expect there to be no problems using NLK with either of those solutions.

Thanks for your question!
