### ISSUE TITLE
NLK Basic Auth Support

### ISSUE THREAD

**Issue by oguzhancelikarslan** [nginxinc/nginx-loadbalancer-kubernetes#173]
### Is your feature request related to a problem? Please describe
The /api endpoint on the server I set up with Nginx Plus is protected with basic authentication. However, NLK cannot access this endpoint, and I believe this is an important feature. 

### Describe the solution you'd like
We can store a password for BasicAuth in the Secret. If the application finds this field filled, it should use it. 

### Additional context
When I examined the Nginx Plus Go Client, I noticed that such a structure does not exist, and it seems that development needs to be done there as well.

**Comment by brianehlert** [comment]
The TLS option to secure traffic support mTLS, which also meets an authentication requirement.
Is there something specific that I am missing?

**Comment by oguzhancelikarslan2** [comment]
> The TLS option to secure traffic support mTLS, which also meets an authentication requirement. Is there something specific that I am missing?

How? Could you share the documentation for that? I only want NLK to access this /api endpoint. I do not want any pod to reach it via a private IP or any client to access it using any tools.

**Comment by oguzhancelikarslan** [comment]
> The TLS option to secure traffic support mTLS, which also meets an authentication requirement. Is there something specific that I am missing?

How? Could you share the documentation for that? I only want NLK to access this /api endpoint. I do not want any pod to reach it via a private IP or any client to access it using any tools.

**Comment by oguzhancelikarslan** [comment]
@brianehlert Yes, you are correct. However, when I use it, I also have to manage certificates such as renewal on all of the Nginx servers as well as within Kubernetes. Basic authentication can expedite my work when I need to prepare a prototype or some people might not want to use mTLS instead of basic authentication.

**Comment by oguzhancelikarslan** [comment]
@brianehlert TLS option solved my problem.
