### ISSUE TITLE
Routing question / VXLAN

### ISSUE THREAD

**Issue by jo-carter** [nginxinc/nginx-loadbalancer-kubernetes#77]
Hello,

More a question than a feature request. 

Does this work without ibgp peering / calico / pods having routable IPs from outside of the cluster ?

and if not, are there any plans to introduce a model similar to Big IP Controller where traffic is tunneled into the cluster from the external NGINX load balancer over VXLAN (or some other layer 2/3 tunnel) ? 

Thanks.

**Comment by chrisakker** [comment]
Hi Jo, sorry I missed your comment for a few weeks.

Yes, peering or tunneling is NOT required, just native IP packets.  All you need is IP connectivity between the Nginx LB Server, and the K8s node IPs ( same subnet, preferably ).  If you look at the diagrams, you will see the Nginx Server on 10.1.1.4,5;  and the K8s nodes on 10.1.1.8,10.

I have a completely separate Whitepaper using **NginxPlus, Quagga BGP, Calico, and Nginx Ingress Controller**.  If this is what you want, check it out:  https://www.nginx.com/resources/library/get-me-to-the-cluster/

We have several large customer with BGP backbones doing this on Premise.

So you have TWO options for getting traffic to your Clusters with Nginx.  One with BGP, one without.

**Comment by chrisakker** [comment]
Closed
